// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fobpfyuosljcnjoupfkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvYnBmeXVvc2xqY25qb3VwZmttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDM5ODQsImV4cCI6MjA1OTc3OTk4NH0.Gxrh0vCWkKPXB7cgPnyjToiNwFmEzUfwkmVKi97eKDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);